#!/bin/bash

create_dir() {
    if [ ! -d /etc/opendkim/keys/$1 ]; then
        echo "$1: creating key directory /etc/opendkim/keys/$1"
        install -o opendkim -g mail -m 750 -d /etc/opendkim/keys/$1
    fi
}

create_new_key() {
    if [ ! -f /etc/opendkim/keys/$1/$2.private ]; then
        echo "$1: creating key /etc/opendkim/keys/$1/$2.private"
        opendkim-genkey -D /etc/opendkim/keys/$1 -d $1 -s $2 -r
        chown opendkim.mail /etc/opendkim/keys/$1/$2.*
    fi
}

gen_zonefile() {
    echo "$1: creating zone file fragment $2/$1.dkim.zone"
    find /etc/opendkim/keys/$1 -name '*.txt' \
        | sort \
        | xargs cat \
        > $2/$1.dkim.zone
}

gen_key_table() {
    echo "generating key table"
    find /etc/opendkim/keys -name '*.private' \
        | { while read fn ; do
                dom=$(sed 's_/etc/opendkim/keys/\(.*\)/.*\.private_\1_' <<< "$fn")
                tag=$(sed 's_/etc/opendkim/keys/.*/\(.*\)\.private_\1_' <<< "$fn")
                printf '%-31s %s:%s:%s\n' "$dom-$tag" "$dom" "$tag" "$fn"
            done ; } \
        | sort \
        > /etc/opendkim/key.table
}

gen_signing_table() {
    echo "generating signing table"
    find /etc/opendkim/keys -mindepth 1 -type d \
        | { while read dn ; do
                dom=$(sed 's_/etc/opendkim/keys/__' <<< "$dn")
                tag=$(ls -tR $dn/*.txt | head -1 | sed "s_/etc/opendkim/keys/$dom/__; s_\\.txt__")
                printf '%-31s %s\n' "*@$dom" "$dom-$tag"
            done ; } \
        | sort \
        > /etc/opendkim/signing.table
}

[ "$DEBUG" = 1 ] && set -x

exec &> >(logger -t $(basename $0))

if [ $# -eq 0 ]; then
    set -- $ZONES
fi

if [ $# -eq 0 ]; then
    echo "error: missing hostnames" >&2
    exit 1
fi

for zone in "$@"; do
    create_dir "$zone"
    create_new_key "$zone" $(date +%Y%m)
    gen_zonefile "$zone" "/var/bind"
done

gen_key_table
gen_signing_table

pkill -USR1 1
