#!/usr/bin/env -S docker-compose -f

version: '3.5'

services:

    ambient:
        build: minidlna
        image: minidlna
        networks: [net]
        cap_add: [NET_ADMIN]
        volumes:
            - /dev/log:/dev/log
            - ${MUSIC_PATH}/Ambient:/opt:ro
        hostname: ambient

    classical:
        image: minidlna
        networks: [net]
        cap_add: [NET_ADMIN]
        volumes:
            - /dev/log:/dev/log
            - ${MUSIC_PATH}/Classical:/opt:ro
        hostname: classical

    dub_and_reggae:
        image: minidlna
        networks: [net]
        cap_add: [NET_ADMIN]
        volumes:
            - /dev/log:/dev/log
            - ${MUSIC_PATH}/Dub & Reggae:/opt:ro
        hostname: dub_and_reggae

    dubstep:
        image: minidlna
        networks: [net]
        cap_add: [NET_ADMIN]
        volumes:
            - /dev/log:/dev/log
            - ${MUSIC_PATH}/Dubstep:/opt:ro
        hostname: dubstep

    electronic:
        image: minidlna
        networks: [net]
        cap_add: [NET_ADMIN]
        volumes:
            - /dev/log:/dev/log
            - ${MUSIC_PATH}/Electronic:/opt:ro
        hostname: electronic

    hiphop:
        image: minidlna
        networks: [net]
        cap_add: [NET_ADMIN]
        volumes:
            - /dev/log:/dev/log
            - ${MUSIC_PATH}/Hip-Hop:/opt:ro
        hostname: hiphop

    metal_punk_and_surf:
        image: minidlna
        networks: [net]
        cap_add: [NET_ADMIN]
        volumes:
            - /dev/log:/dev/log
            - ${MUSIC_PATH}/Metal & Punk & Surf:/opt:ro
        hostname: metal_punk_and_surf

    triphop_and_turntables:
        image: minidlna
        networks: [net]
        cap_add: [NET_ADMIN]
        volumes:
            - /dev/log:/dev/log
            - ${MUSIC_PATH}/Trip-Hop & Turntables:/opt:ro
        hostname: triphop_and_turntables

    weird_and_pop:
        image: minidlna
        networks: [net]
        cap_add: [NET_ADMIN]
        volumes:
            - /dev/log:/dev/log
            - ${MUSIC_PATH}/Weird & Pop:/opt:ro
        hostname: weird_and_pop

networks:
    net:
        driver: macvlan
        driver_opts:
            parent: mac0
