#!/usr/bin/env -S docker-compose -f

version: '3.5'

services:

    openvpn_config:
        networks:
            - net
        build: openvpn_config
        env_file: openvpn_config/vpn.conf
        volumes:
            - vpn_config:/etc/vpnconfig

    openvpn:
        build: openvpn
        networks:
            - net
        privileged: true
        volumes:
            - vpn_config:/etc/vpnconfig
        depends_on:
            - openvpn_config

    transmission:
        build: transmission
        networks:
            - net
        cap_add:
            - NET_ADMIN
        ports:
            - "9091:9091"
        depends_on:
            - openvpn

    privoxy:
        build: privoxy
        networks:
            - net
            - safe
        cap_add:
            - NET_ADMIN
        ports:
            - "8118:8118"
        depends_on:
            - openvpn

volumes:
    vpn_config: ~

networks:
    net:
        driver: bridge
        driver_opts:
            com.docker.network.bridge.name: br-vpn
        ipam:
            driver: default
            config:
                - subnet: 172.28.5.0/24

    safe:
        driver: bridge
        driver_opts:
            com.docker.network.bridge.name: br-vpn-safe
        ipam:
            driver: default
            config:
                - subnet: 172.28.6.0/24
