#!/bin/bash -x
backup()  { docker run --rm -v $1:/$1 -v $(pwd)/volumes:/volumes alpine:3.8 tar cvzf volumes/$1.tar.gz $1; }
restore() { docker run --rm -v $1:/$1 -v $(pwd)/volumes:/volumes alpine:3.8 tar xvzf volumes/$1.tar.gz;    }
for volume in dkim dns mail; do $1 $volume; done
