#!/bin/bash -x
dkim() { docker run --rm -v dkim:/dkim -v $(pwd)/volumes:/volumes alpine:3.8 ; }
dns() { docker run --rm -v dns:/dns -v $(pwd)/volumes:/volumes alpine:3.8 ; }
case "$1" in
    backup)
        docker run --rm -v dkim:/dkim -v $(pwd)/volumes:/volumes alpine:3.8 tar cvzf volumes/dkim.tar.gz dkim
        docker run --rm -v dns:/dns -v $(pwd)/volumes:/volumes alpine:3.8 tar cvzf volumes/dns.tar.gz dns
        ;;
    restore)
        docker run --rm -v dkim:/dkim -v $(pwd)/volumes:/volumes alpine:3.8 tar xvzf volumes/dkim.tar.gz
        docker run --rm -v dns:/dns -v $(pwd)/volumes:/volumes alpine:3.8 tar xvzf volumes/dns.tar.gz
        ;;
esac
