FROM alpine:3.7
RUN apk --no-cache upgrade
RUN apk --no-cache add dovecot
#COPY dovecot/entrypoint.sh /entrypoint.sh
#ENTRYPOINT ["/entrypoint.sh"]
#CMD ["start"]
CMD ["/usr/sbin/dovecot", "-F", "-c", "/etc/dovecot/dovecot.conf"]
