version: '3.5'

services:

    openldap:
        build: openldap
        ports:
            - "389:389"

    postfix:
        build: postfix

    dovecot:
        build: dovecot

    postgrey:
        build: postgrey

    policyd_spf:
        build: policyd_spf

    opendkim:
        build: opendkim

    openvpn_config:
        build: openvpn_config
        env_file: openvpn_config/vpn.conf
        volumes:
            - vpn_config:/etc/vpnconfig

    openvpn:
        build: openvpn
        privileged: true
        volumes:
            - vpn_config:/etc/vpnconfig
        depends_on:
            - openvpn_config

    transmission:
        build: transmission
        cap_add:
            - NET_ADMIN
        ports:
            - "9091:9091"
        depends_on:
            - openvpn

    privoxy:
        build: privoxy
        networks:
            - default
            - vpn
        cap_add:
            - NET_ADMIN
        ports:
            - "8118:8118"
        depends_on:
            - openvpn

    # samba
    # nfs
    # dlna
    # cupsd

    # bind9

    # graylog/ELK/splunk

    # python apps

volumes:
    vpn_config: ~

networks:
    default: ~

    vpn:
        driver: bridge
        ipam:
            driver: default
            config:
            - subnet: 172.66.6.0/24
