#!/usr/bin/env -S docker-compose -f

version: '3.5'

services:

    openldap:
        build: openldap
        ports:
            - "389:389"
        networks:
            - net

    cron:
        build: cron
        networks:
            - net
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            SMTPHOST: postfix

networks:
    net:
        driver: bridge
        driver_opts:
            com.docker.network.bridge.name: br-sys
        ipam:
            driver: default
            config:
                - subnet: 172.28.1.0/24
