#!/usr/bin/env -S docker-compose -f

version: '3.5'

services:

    slapd:
        build: openldap
        ports:
            - "389:389"
        networks:
            - net
        volumes:
            - /dev/log:/dev/log

    cron:
        build: cron
        networks:
            - net
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            SMTPHOST: postfix

    syslog:
        build: rsyslog
        image: joostm/alpine_rsyslog:3.8
        environment:
            RSYSLOG_LISTEN: "514"
            RSYSLOG_LOCAL: "1"
        networks:
            - net

networks:
    net: ~
