#!/usr/bin/env -S docker-compose -f

version: '3.7'

services:

    bind9:
        build: bind
        image: bind
        networks:
            - net
        volumes:
            - dns:/var/lib/dns

networks:
    net:
        driver: bridge
        driver_opts:
            com.docker.network.bridge.name: br-dns
        ipam:
            driver: default
            config:
                - subnet: 172.28.2.0/24

volumes:
    dns:
        external: true
