#!/usr/bin/env -S docker-compose -f

version: '3.5'

services:

    postfix:
        build: postfix
        networks:
            - net
        volumes:
            - /dev/log:/dev/log

    dovecot:
        build: dovecot
        networks:
            - net
            - user

    postgrey:
        build: postgrey
        networks:
            - net

    policyd_spf:
        build: policyd_spf
        networks:
            - net

    opendkim:
        build: opendkim
        networks:
            - net

networks:
    net: ~

    user:
        external:
            name: user_net
