#!/usr/bin/env -S docker-compose -f

version: '3.5'

services:

    postfix:
        build: postfix
        networks: [net, sys]

    dovecot:
        build: dovecot
        networks:
            - net
            - sys
        volumes:
            - /dev/log:/dev/log
            - mail:/home

    postgrey:
        build: postgrey
        networks:
            - net
        volumes:
            - /dev/log:/dev/log

    policyd_spf:
        build: policyd_spf
        networks:
            - net
        volumes:
            - /dev/log:/dev/log

    opendkim:
        build: opendkim
        networks:
            - net
        volumes:
            - /dev/log:/dev/log
            - dkim:/var/lib/dkim
            - dns:/var/lib/dns
        environment:
            ZONES: j0057.nl pk28.nl punosqnp.nl stomrin.nl mlnr.eu molenaar.email

networks:
    net: ~

    sys:
        external:
            name: sys_net

volumes:
    dkim:
        external: true

    dns:
        external: true

    mail:
        external: true
