#!/usr/bin/env -S docker-compose -f

version: '3.5'

services:

    postfix:
        build: postfix
        networks:
            - net
            - sys
        volumes:
            - /dev/log:/dev/log

    dovecot:
        build: dovecot
        networks:
            - net
            - sys
        volumes:
            - /dev/log:/dev/log

    postgrey:
        build: postgrey
        networks:
            - net
        volumes:
            - /dev/log:/dev/log

    policyd_spf:
        build: policyd_spf
        networks:
            - net
        volumes:
            - /dev/log:/dev/log

    opendkim:
        build: opendkim
        networks:
            - net
        volumes:
            - /dev/log:/dev/log

networks:
    net: ~

    sys:
        external:
            name: sys_net
