version: '3.6'

services:

    elasticsearch:
        image: blacktop/elasticsearch:latest
        hostname: elasticsearch
        ports:
            - '9200:9200'

    kibana:
        image: blacktop/kibana:latest
        #init: true
        hostname: kibana
        ports:
            - '32769:5601'
        environment:
            KIBANA_ELASTICSEARCH_URL: http://elasticsearch:9200/           

    grafana:
        image: grafana/grafana:latest
        hostname: grafana
        ports:
            - '32770:3000'

    influxdb:
        image: library/influxdb:latest
        hostname: influxdb
        ports:
            - '32771:8086'
        environment:
            INFLUXDB_REPORTING_DISABLED: 'true'

    chronograf:
        image: library/chronograf:alpine
        hostname: chronograf
        ports:
            - '32772:8888'
        #command: chronograf --influxdb=http://influxdb:8086
