#!/usr/bin/env -S docker-compose -f

version: '3.5'

services:

    slapd:
        build: openldap
        ports:
            - "389:389"
        networks:
            - net
        volumes:
            - /dev/log:/dev/log

networks:
    net: ~
